"""add resume_uploaded_at and history table

Revision ID: 4a6589f74ce4
Revises: 2f7a9b1c3d4e
Create Date: 2026-02-08 22:56:25.080542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6589f74ce4'
down_revision: Union[str, Sequence[str], None] = '2f7a9b1c3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_resumes', sa.Column('resume_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_apaar_id'), 'users', ['apaar_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_apaar_id'), table_name='users')
    op.drop_column('student_resumes', 'resume_uploaded_at')
    op.add_column('employer_profiles', sa.Column('is_phone_verified', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('employer_profiles', sa.Column('email_otp_expires', sa.VARCHAR(), nullable=True))
    op.add_column('employer_profiles', sa.Column('phone_otp_code', sa.VARCHAR(), nullable=True))
    op.add_column('employer_profiles', sa.Column('phone_otp_expires', sa.VARCHAR(), nullable=True))
    op.add_column('employer_profiles', sa.Column('email_otp_code', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
