"""added_student_profile_wizard_fields

Revision ID: 604842507a76
Revises: 8ae08471e5d0
Create Date: 2026-01-22 16:32:49.050557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604842507a76'
down_revision: Union[str, Sequence[str], None] = '8ae08471e5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('current_city', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('profile_type', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('start_year', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('interests', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('looking_for', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('work_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'work_mode')
    op.drop_column('student_profiles', 'looking_for')
    op.drop_column('student_profiles', 'interests')
    op.drop_column('student_profiles', 'end_year')
    op.drop_column('student_profiles', 'start_year')
    op.drop_column('student_profiles', 'profile_type')
    op.drop_column('student_profiles', 'languages')
    op.drop_column('student_profiles', 'gender')
    op.drop_column('student_profiles', 'current_city')
    op.drop_column('student_profiles', 'last_name')
    op.drop_column('student_profiles', 'first_name')
    # ### end Alembic commands ###
