"""Add institute_id and cgpa to student_profiles

Revision ID: 6f8ca954c7e1
Revises: e512d5d207c5
Create Date: 2026-02-02 10:47:32.326259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8ca954c7e1'
down_revision: Union[str, Sequence[str], None] = 'e512d5d207c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('cgpa', sa.String(), nullable=True))
    op.create_foreign_key(None, 'student_profiles', 'institute_profiles', ['institute_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'cgpa')
    op.drop_column('student_profiles', 'institute_id')
    # ### end Alembic commands ###
