"""Add email verification fields to User model

Revision ID: 8ae08471e5d0
Revises: d9eca61042ba
Create Date: 2026-01-15 18:51:52.203102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae08471e5d0'
down_revision: Union[str, Sequence[str], None] = 'd9eca61042ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_aishe_code_uc', 'institute_profiles', ['aishe_code'])
    op.create_index(op.f('ix_institute_profiles_id'), 'institute_profiles', ['id'], unique=False)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_index(op.f('ix_institute_profiles_id'), table_name='institute_profiles')
    op.drop_constraint('_aishe_code_uc', 'institute_profiles', type_='unique')
    # ### end Alembic commands ###
