"""Sync user schema

Revision ID: 9cd7661733fd
Revises: 604842507a76
Create Date: 2026-01-22 17:18:10.828277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd7661733fd'
down_revision: Union[str, Sequence[str], None] = '604842507a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We are skipping dropping tables that might be useful later or are not related to this fix
    # op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    # op.drop_table('feedback')
    # op.drop_table('student_credits')
    # op.drop_table('credit_rules')
    
    # Check if columns exist before adding them (although alembic usually handles this, we want to be safe if partial migration happened)
    # But for now, we will trust alembic's detection that these columns are missing from the DB
    
    # Focusing on USERS table fix first as that is the critical error
    # op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    # ...
    
    # Wait, the error said "column users.email does not exist". 
    # But looking at the migration, it wants to ADD email and DROP username.
    # This means the database currently has 'username' but not 'email'.
    # This matches the error.
    
    # Let's apply the User changes.
    # Because there are existing rows, we cannot add non-nullable columns directly.
    # 1. Add columns as nullable first
    # op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    
    # op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # 2. Populate new columns with data from old columns or defaults
    # For email, we use username if it looks like email, or just dummy
    # op.execute("UPDATE users SET email = username WHERE email IS NULL")
    # If username was not email, this might be bad, but it's dev env.
    
    # For hashed_password, we copy password_hash
    # op.execute("UPDATE users SET hashed_password = password_hash WHERE hashed_password IS NULL")
    
    # For full_name, we use username as fallback
    # op.execute("UPDATE users SET full_name = username WHERE full_name IS NULL")
    
    # 3. Now alter columns to be non-nullable if needed
    # op.alter_column('users', 'email', nullable=False)
    # op.alter_column('users', 'hashed_password', nullable=False)
    # op.alter_column('users', 'full_name', nullable=False)

    # Drop old columns if they exist
    # op.drop_index('ix_users_username', table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # op.drop_column('users', 'password_hash')
    # op.drop_column('users', 'username')
    
    # Ignoring internship changes for now to avoid side effects, we just want login to work
    # If internships table needs update, we can do it later or uncomment below if we are sure
    # The migration detected changes in internships too. Let's comment them out to reduce risk of data loss on other tables
    # unless they are critical. The error was about users.email.
    
    # op.add_column('internships', sa.Column('employer_id', sa.Integer(), nullable=False))
    # ... (other internship changes)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.add_column('internships', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('internships', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('internships', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('internships', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('internships', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'internships', type_='foreignkey')
    op.create_index(op.f('ix_internships_student_id'), 'internships', ['student_id'], unique=False)
    op.create_index(op.f('ix_internships_company_id'), 'internships', ['company_id'], unique=False)
    op.drop_column('internships', 'duration_weeks')
    op.drop_column('internships', 'mode')
    op.drop_column('internships', 'location')
    op.drop_column('internships', 'description')
    op.drop_column('internships', 'title')
    op.drop_column('internships', 'employer_id')
    op.create_table('credit_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('min_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_rules_pkey'))
    )
    op.create_table('student_credits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('internship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'ADJUSTED', name='credit_status_enum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], name=op.f('student_credits_internship_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_credits_pkey')),
    sa.UniqueConstraint('internship_id', name=op.f('student_credits_internship_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('internship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], name=op.f('feedback_internship_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('feedback_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###
