"""added internship skills table

Revision ID: b23f0ef1af36
Revises: 54f6719449a6
Create Date: 2026-01-07 20:45:56.643644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23f0ef1af36'
down_revision: Union[str, Sequence[str], None] = '54f6719449a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_id', 'skill_id', name='_intern_skill_uc')
    )
    op.create_index(op.f('ix_internship_skills_id'), 'internship_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internship_skills_id'), table_name='internship_skills')
    op.drop_table('internship_skills')
    # ### end Alembic commands ###
