"""empty message

Revision ID: d9eca61042ba
Revises: b23f0ef1af36
Create Date: 2026-01-14 23:53:05.750241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9eca61042ba'
down_revision: Union[str, Sequence[str], None] = 'b23f0ef1af36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('apaar_id', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('is_apaar_verified', sa.Boolean(), nullable=True))
    op.add_column('student_profiles', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('university_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('projects', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'student_profiles', ['apaar_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='unique')
    op.drop_column('student_profiles', 'projects')
    op.drop_column('student_profiles', 'skills')
    op.drop_column('student_profiles', 'degree')
    op.drop_column('student_profiles', 'university_name')
    op.drop_column('student_profiles', 'phone_number')
    op.drop_column('student_profiles', 'full_name')
    op.drop_column('student_profiles', 'is_apaar_verified')
    op.drop_column('student_profiles', 'apaar_id')
    # ### end Alembic commands ###
