  """add_user_id_notification

Revision ID: edc1164dfbad
Revises: 4a6589f74ce4
Create Date: 2026-02-18 18:53:53.730685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc1164dfbad'
down_revision: Union[str, Sequence[str], None] = '4a6589f74ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('notifications')]

    # 1. Add user_id as nullable first
    if 'user_id' not in columns:
        with op.batch_alter_table('notifications') as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 2. Backfill data
    op.execute("""
        UPDATE notifications 
        SET user_id = (
            SELECT user_id 
            FROM student_profiles 
            WHERE student_profiles.id = notifications.student_id
        )
    """)
    
    # Remove notifications that couldn't be mapped (orphaned)
    op.execute("DELETE FROM notifications WHERE user_id IS NULL")

    # 3. Apply constraints and schema changes using batch mode for SQLite support
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key('fk_notifications_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('student_id')
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('(FALSE)'))

    # Other changes from original generation
    # op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    # op.drop_table('login_history')
    
    # with op.batch_alter_table('student_profiles') as batch_op:
    #     batch_op.drop_column('phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('phone_number', sa.VARCHAR(), nullable=True))
    op.add_column('notifications', sa.Column('student_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'student_profiles', ['student_id'], ['id'])
    op.alter_column('notifications', 'is_read',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.drop_column('notifications', 'user_id')
    op.create_table('login_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('login_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    # ### end Alembic commands ###
