# Generated by Django 6.0.1 on 2026-01-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_request', to='internships.application'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='credit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credits.creditrequest'),
        ),
    ]
