from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from django.db.models import Sum

from internships.models import Application
from credits.models import CreditRequest

class CustomAuthToken(ObtainAuthToken):
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user_id': user.pk,
            'email': user.email,
            'role': user.role
        })

class StudentDashboard(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        if request.user.role != 'student':
            return Response({"error": "Unauthorized"}, status=403)
        
        # Total Credits (Approved only)
        approved_credits = CreditRequest.objects.filter(
            application__student=request.user, 
            status='APPROVED'
        ).aggregate(total=Sum('calculated_credits'))['total'] or 0

        # Internship List (Applied)
        applications = Application.objects.filter(student=request.user).values(
            'internship__title', 'status', 'credit_request__status', 'credit_request__calculated_credits'
        )

        # Analytics Data
        ugc_credits = CreditRequest.objects.filter(
            application__student=request.user, 
            status='APPROVED',
            policy='UGC'
        ).aggregate(total=Sum('calculated_credits'))['total'] or 0

        aicte_credits = CreditRequest.objects.filter(
            application__student=request.user, 
            status='APPROVED',
            policy='AICTE'
        ).aggregate(total=Sum('calculated_credits'))['total'] or 0

        return Response({
            "total_credits": approved_credits,
            "internships": applications,
            "analytics": {
                "UGC": ugc_credits,
                "AICTE": aicte_credits
            }
        })

class CompanyDashboard(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        if request.user.role != 'company':
            return Response({"error": "Unauthorized"}, status=403)
        
        total_applicants = Application.objects.filter(internship__company=request.user).count()
        completed_internships = Application.objects.filter(internship__company=request.user, status='completed').count()
        
        # Credits Generated by this company's internships
        credits_generated = CreditRequest.objects.filter(
            application__internship__company=request.user,
            status='APPROVED'
        ).aggregate(total=Sum('calculated_credits'))['total'] or 0

        return Response({
            "total_applicants": total_applicants,
            "completed_internships": completed_internships,
            "credits_generated": credits_generated
        })

class InstituteDashboard(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        if request.user.role != 'institute':
            return Response({"error": "Unauthorized"}, status=403)
        
        total_issued = CreditRequest.objects.filter(status='APPROVED').aggregate(total=Sum('calculated_credits'))['total'] or 0
        ugc_total = CreditRequest.objects.filter(status='APPROVED', policy='UGC').aggregate(total=Sum('calculated_credits'))['total'] or 0
        aicte_total = CreditRequest.objects.filter(status='APPROVED', policy='AICTE').aggregate(total=Sum('calculated_credits'))['total'] or 0
        
        pending_approvals = CreditRequest.objects.filter(status='ASSIGNED').count()
        
        return Response({
            "total_credits_issued": total_issued,
            "policy_distribution": {
                "UGC": ugc_total,
                "AICTE": aicte_total
            },
            "pending_approvals": pending_approvals
        })
